backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
media_folder: "images"
public_folder: "/images"

display_url: https://www.aramisprod.com
locale: fr
# to be able to run "npx netlify-cms-proxy-server" for local backend
local_backend: true

collections:
  - label: "Video"
    name: "videos"
    folder: "video"
    create: true
    editor:
      preview: true
    sortable_fields: ["position"]
    view_groups:
      - label: Catégorie
        field: tags
    fields:
      - { label: "Youtube URL", name: "url", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - label: "Position"
        name: "position"
        widget: "number"
        value_type: int
      - widget: select
        label: "Catégories"
        name: "tags"
        multiple: true
        create: true
        options: ["video", "musique", "documentaire", "stop-motion", "drones"]
