backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
media_folder: "images"
public_folder: "/images"

# to be able to run "npx netlify-cms-proxy-server" for local backend
# local_backend: true

collections:
  - label: "Video"
    name: "videos"
    folder: "video"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Youtube URL", name: "url", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
